spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.NonRegisteringDriver
    url: jdbc:mysql://192.168.0.104:3306/fornecedor
    username: root
    password: JoceO2020!@
  jpa:
    properties:
      hibernate:
        ddl-auto: update
